---
- name: 'Prep'
  ansible.builtin.import_tasks: 'prep.yml'

- name: 'Maintenance'
  when: gcp_ddns_flg_maintenance
  ansible.builtin.import_tasks: 'maintenance.yml'

- name: 'Install'
  when: gcp_ddns_flg_install
  ansible.builtin.import_tasks: 'install.yml'

- name: 'Config'
  when: gcp_ddns_flg_config
  ansible.builtin.import_tasks: 'config.yml'

- name: 'Start'
  when: not (molecule_flg_test | default(false))
  ansible.builtin.import_tasks: 'start.yml'
