---
###############################################################################
# Verify
###############################################################################

- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ gcp_ddns___app._bin }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ gcp_ddns___app._bin }}'
        test_file: '{{ gcp_ddns___app._bin }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
        test_diff: true

    - name: '{{ "Verify | test | " ~ gcp_ddns___app._dns_key }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ gcp_ddns___app._dns_key }}'
        test_file: '{{ gcp_ddns___app._dns_key }}'
        test_owner: 'gcp_ddns'
        test_group: 'gcp_ddns'
        test_mode: '0640'
        test_state: 'file'
        test_diff: true
